---
version: "3.7"
name: scylla

networks:
  scylla:
    driver: bridge

volumes:
  scylla-0: null
  scylla-1: null
  scylla-2: null

services:
  scylla-0:
    image: scylladb/scylla:5.1.6
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - ./scylla/scylla.yml:/etc/scylla/scylla.yml
      - ./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties
      - scylla-0:/var/lib/scylla
    networks:
      - scylla

  scylla-1:
    image: scylladb/scylla:5.1.6
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - ./scylla/scylla.yml:/etc/scylla/scylla.yml
      - ./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties
      - scylla-1:/var/lib/scylla
    networks:
      - scylla

  scylla-2:
    image: scylladb/scylla:5.1.6
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - ./scylla/scylla.yml:/etc/scylla/scylla.yml
      - ./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties
      - scylla-2:/var/lib/scylla
    networks:
      - scylla
